// ─────────────────────────────────────────────────────────────────────────
// Cloudflare Pages Function — GET /api/og/:payload
//
// The og:image: renders the design's REAL achievement — the same
// src/Achievement.jsx composition Studio's preview and the free export use
// — to an SVG string, then rasterises it to PNG via @resvg/resvg-wasm. This
// is the viral hook: a shared link unfurls with the actual coat of arms, not
// a generic logo card.
//
// BUNDLING (see scripts/build-achievement-bundle.mjs's header for the full
// story): Achievement.jsx statically imports its 10 vendored-furniture SVGs
// via Vite's `?raw` suffix. Cloudflare's Pages Functions bundler doesn't
// understand that suffix (confirmed: "No loader is configured for '.svg'
// files"). Rather than touch Achievement.jsx — Task 12's SSR seam is reused
// EXACTLY here, not re-architected — a prebuild step resolves `?raw` ahead
// of time into functions/_lib/achievement.generated.mjs (committed,
// regenerated by the pretest/build npm scripts), which this Function
// imports directly. react/react-dom/react-dom/server stay external in that
// bundle; THIS file's own imports of them resolve via ordinary node_modules
// resolution, which Cloudflare's Functions bundler already handles natively
// (confirmed live, see task-17-report.md).
//
// WASM: functions/_lib/resvg.js — see that file's header for how the
// @resvg/resvg-wasm binary loads in this runtime (a direct `.wasm` ESM
// import; no wrangler.toml config needed).
//
// backfill=false (REQUIRED — Task 14 review finding, folded into this task's
// brief): render EXACTLY the stored design. The shared design may have had a
// part deliberately "set aside" (e.g. the user removed the crest) —
// backfill=true would silently re-seed that part from
// withDefaultAchievement, so the share preview would show a crest the user
// chose to delete. `resolveAchievementArt` (functions/_lib/achievementArt.js)
// mirrors this: it never backfills either, so it only ever prefetches art
// for parts the design ACTUALLY carries.
//
// ssr=true: the shield slot always renders the local <Shield> — the
// drawshield.net <foreignObject>/<img> fallback does not survive
// renderToStaticMarkup → resvg (<foreignObject> has no meaning to a static
// SVG rasteriser). An out-of-vocab escutcheon degrades to whatever <Shield>
// can draw locally instead — Task 12's own documented, acceptable fallback.
// ─────────────────────────────────────────────────────────────────────────

import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import Achievement from '../../_lib/achievement.generated.mjs';
import { decodeCoat } from '../../../src/share/codec.js';
import { resolveAchievementArt } from '../../_lib/achievementArt.js';
import { svgToPng } from '../../_lib/resvg.js';
import { OG_WIDTH, OG_HEIGHT } from '../../_lib/ogImage.js';

// Achievement's own fixed canvas (src/achievement-art/layout.js LAYOUT.viewBox).
const ACH_W = 1000;
const ACH_H = 1200;

// C.bg (src/theme.js) — the app's own dark base surface, so the letterboxed
// og:image reads as "the same product", not a mismatched flat white/black.
const BG = '#090C13';

/** Build the composed SVG document: solid brand background, the real
 *  achievement centred/letterboxed onto the fixed OG canvas. */
export function buildOgSVG(achievementSVG) {
  const x = (OG_WIDTH - ACH_W) / 2;
  const y = (OG_HEIGHT - ACH_H) / 2;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${OG_WIDTH}" height="${OG_HEIGHT}" viewBox="0 0 ${OG_WIDTH} ${OG_HEIGHT}">` +
    `<rect width="${OG_WIDTH}" height="${OG_HEIGHT}" fill="${BG}"/>` +
    `<svg x="${x}" y="${y}" width="${ACH_W}" height="${ACH_H}" viewBox="0 0 ${ACH_W} ${ACH_H}" preserveAspectRatio="xMidYMid meet">${achievementSVG}</svg>` +
    `</svg>`
  );
}

/** Render the achievement (real art prefetched) to a static SVG string.
 *  Exported for tests that only want to assert the pre-resvg markup. */
export async function renderAchievementSVG(coat) {
  const artCache = await resolveAchievementArt(coat);
  return renderToStaticMarkup(
    React.createElement(Achievement, { design: coat, ssr: true, backfill: false, artCache }),
  );
}

export async function onRequestGet({ params, request }) {
  let coat;
  try {
    coat = await decodeCoat(params.payload);
  } catch {
    return Response.redirect(new URL('/', request.url), 302);
  }

  let png;
  try {
    const achievementSVG = await renderAchievementSVG(coat);
    png = await svgToPng(buildOgSVG(achievementSVG), { width: OG_WIDTH });
  } catch {
    // Never ship a broken/blank image — a missing OG image is recoverable
    // (the client falls back to the platform's own default preview); a
    // silently-broken one is not.
    return new Response('og_render_failed', { status: 500, headers: { 'content-type': 'text/plain' } });
  }

  // Content-addressed by payload — the payload fully determines the image,
  // so it's safe to cache forever.
  return new Response(png, {
    status: 200,
    headers: { 'content-type': 'image/png', 'cache-control': 'public, max-age=31536000, immutable' },
  });
}
