// Generated by scripts/vendor-components.mjs — DO NOT hand-edit.
// Metadata for the bundled achievement-furniture SVGs (helmets, torse,
// mantling, motto scrolls, a token compartment) vendored from DrawShield's
// svg/components/ tree. Unlike src/charges (2,108 files on R2), these ~10
// files are always needed to draw a full achievement, so they're bundled
// in-repo rather than fetched from object storage.
//
// This module is intentionally Vite-agnostic (no import.meta.glob / ?raw) so
// it loads under plain `node --test` as well as under Vite. `path` is
// relative to this file's directory (src/achievement-art/) — import the raw
// SVG text at build time with Vite's `?raw` suffix, e.g.:
//   import svg from './achievement-art/helmet/royal.svg?raw'
// or, to pull every file's text at once:
//   import.meta.glob('./achievement-art/**/*.svg', { query: '?raw', import: 'default', eager: true })
//
// recolorIds.colour / recolorIds.metal: element ids whose fill DrawShield
// swaps for the shield's first colour / first metal tincture respectively
// (mantling matches the field's principal colour, lined with the principal
// metal; the torse alternates the same two tinctures in 3+3 twists).
// textPathId: the id of the <path> a <textPath> should reference to letter
// the motto along the scroll's curve.

export const HELMETS = [
  {
    "key": "royal",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/royal.svg",
    "viewBox": "0 0 270.013 316.914",
    "rank": "royal",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Sodacan",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Sodacan"
    }
  },
  {
    "key": "peer",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/peer.svg",
    "viewBox": "0 0 491.823 651.269",
    "rank": "peer",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Zigeuner",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Zigeuner"
    }
  },
  {
    "key": "baronet",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/baronet.svg",
    "viewBox": "0 0 729.209 746.244",
    "rank": "baronet",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Orror",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Orror"
    }
  },
  {
    "key": "knight",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/knight.svg",
    "viewBox": "0 0 356.353 477.737",
    "rank": "knight",
    "license": {
      "artist": "http://commons.wikimedia.org/wiki/User:SanglierT",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "http://commons.wikimedia.org/wiki/User:SanglierT"
    }
  },
  {
    "key": "esquire",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/esquire.svg",
    "viewBox": "0 0 691.118 800",
    "rank": "esquire",
    "license": {
      "artist": "https://commons.wikimedia.org/w/index.php?title=User:Raymond1922A",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/w/index.php?title=User:Raymond1922A"
    }
  }
];

export const TORSE = {
  "key": "torse",
  "dir": "torse",
  "kind": "torse",
  "path": "torse/torse.svg",
  "viewBox": "0 0 204.998 42.041",
  "recolorIds": {
    "colour": [
      "tincture1-1",
      "tincture1-2",
      "tincture1-3"
    ],
    "metal": [
      "tincture2-1",
      "tincture2-2",
      "tincture2-3"
    ]
  },
  "license": {
    "artist": "https://commons.wikimedia.org/wiki/User:Sodacan",
    "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
    "source": "https://commons.wikimedia.org/wiki/User:Sodacan"
  }
};

export const MANTLING = [
  {
    "key": "cloak",
    "dir": "mantling",
    "kind": "mantling",
    "path": "mantling/cloak.svg",
    "viewBox": "0 0 1000 1200",
    "recolorIds": {
      "colour": [
        "dexter1-1",
        "sinister1-1"
      ],
      "metal": [
        "dexter2-1",
        "sinister2-1"
      ]
    },
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Bluebear2",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Bluebear2"
    }
  }
];

export const MOTTOS = [
  {
    "key": "scroll-above",
    "dir": "motto",
    "kind": "motto",
    "path": "motto/scroll-above.svg",
    "viewBox": "0 0 956 197",
    "placement": "above",
    "textPathId": "textPath",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg"
    }
  },
  {
    "key": "scroll-below",
    "dir": "motto",
    "kind": "motto",
    "path": "motto/scroll-below.svg",
    "viewBox": "0 0 956 197",
    "placement": "below",
    "textPathId": "textPath",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg"
    }
  }
];

export const COMPARTMENTS = [
  {
    "key": "pedestal",
    "dir": "compartments",
    "kind": "compartment",
    "path": "compartments/pedestal.svg",
    "viewBox": "0 0 889.222 60.056",
    "license": {
      "artist": "(adapted from) http://www.therightproductions.nl/hogeraadvanadel/index.php?id=109&amp;wapen=1868",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://drawshield.net"
    }
  }
];

// All assets, flat — keyed by "dir/key" (matches attribution.json's keys).
export const ACHIEVEMENT_ART = [
  {
    "key": "royal",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/royal.svg",
    "viewBox": "0 0 270.013 316.914",
    "rank": "royal",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Sodacan",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Sodacan"
    }
  },
  {
    "key": "peer",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/peer.svg",
    "viewBox": "0 0 491.823 651.269",
    "rank": "peer",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Zigeuner",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Zigeuner"
    }
  },
  {
    "key": "baronet",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/baronet.svg",
    "viewBox": "0 0 729.209 746.244",
    "rank": "baronet",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Orror",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Orror"
    }
  },
  {
    "key": "knight",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/knight.svg",
    "viewBox": "0 0 356.353 477.737",
    "rank": "knight",
    "license": {
      "artist": "http://commons.wikimedia.org/wiki/User:SanglierT",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "http://commons.wikimedia.org/wiki/User:SanglierT"
    }
  },
  {
    "key": "esquire",
    "dir": "helmet",
    "kind": "helmet",
    "path": "helmet/esquire.svg",
    "viewBox": "0 0 691.118 800",
    "rank": "esquire",
    "license": {
      "artist": "https://commons.wikimedia.org/w/index.php?title=User:Raymond1922A",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/w/index.php?title=User:Raymond1922A"
    }
  },
  {
    "key": "torse",
    "dir": "torse",
    "kind": "torse",
    "path": "torse/torse.svg",
    "viewBox": "0 0 204.998 42.041",
    "recolorIds": {
      "colour": [
        "tincture1-1",
        "tincture1-2",
        "tincture1-3"
      ],
      "metal": [
        "tincture2-1",
        "tincture2-2",
        "tincture2-3"
      ]
    },
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Sodacan",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Sodacan"
    }
  },
  {
    "key": "cloak",
    "dir": "mantling",
    "kind": "mantling",
    "path": "mantling/cloak.svg",
    "viewBox": "0 0 1000 1200",
    "recolorIds": {
      "colour": [
        "dexter1-1",
        "sinister1-1"
      ],
      "metal": [
        "dexter2-1",
        "sinister2-1"
      ]
    },
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/User:Bluebear2",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/User:Bluebear2"
    }
  },
  {
    "key": "scroll-above",
    "dir": "motto",
    "kind": "motto",
    "path": "motto/scroll-above.svg",
    "viewBox": "0 0 956 197",
    "placement": "above",
    "textPathId": "textPath",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg"
    }
  },
  {
    "key": "scroll-below",
    "dir": "motto",
    "kind": "motto",
    "path": "motto/scroll-below.svg",
    "viewBox": "0 0 956 197",
    "placement": "below",
    "textPathId": "textPath",
    "license": {
      "artist": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://commons.wikimedia.org/wiki/File:Gentleman_coat_of_arms_template.svg"
    }
  },
  {
    "key": "pedestal",
    "dir": "compartments",
    "kind": "compartment",
    "path": "compartments/pedestal.svg",
    "viewBox": "0 0 889.222 60.056",
    "license": {
      "artist": "(adapted from) http://www.therightproductions.nl/hogeraadvanadel/index.php?id=109&amp;wapen=1868",
      "license": "CC BY-SA (Wikimedia Commons; treat as share-alike)",
      "source": "https://drawshield.net"
    }
  }
];

export const findByKey = (dir, key) => ACHIEVEMENT_ART.find((a) => a.dir === dir && a.key === key) || null;
